<?php

declare(strict_types=1);

namespace App\Privacy;

use PDO;

final class QuickUnlockRepository
{
    public function __construct(private readonly PDO $pdo) {}
    public function createChallenge(int $userId,string $sessionId,string $purpose,?string $quickId,string $challenge,string $options,string $expiresAt): int { $s=$this->pdo->prepare('INSERT INTO webauthn_challenges (user_id,session_id,purpose,quick_unlock_id,challenge,options_json,expires_at) VALUES (:u,:s,:p,:q,:c,:o,:e)'); $s->bindValue(':u',$userId,PDO::PARAM_INT);$s->bindValue(':s',$sessionId);$s->bindValue(':p',$purpose);$s->bindValue(':q',$quickId);$s->bindValue(':c',$challenge,PDO::PARAM_LOB);$s->bindValue(':o',$options);$s->bindValue(':e',$expiresAt);$s->execute();return(int)$this->pdo->lastInsertId(); }
    public function consumeChallenge(int $id,int $userId,string $sessionId,string $purpose):?array { $s=$this->pdo->prepare('UPDATE webauthn_challenges SET consumed_at=UTC_TIMESTAMP() WHERE id=:id AND user_id=:u AND session_id=:s AND purpose=:p AND consumed_at IS NULL AND expires_at>UTC_TIMESTAMP()');$s->execute([':id'=>$id,':u'=>$userId,':s'=>$sessionId,':p'=>$purpose]);if($s->rowCount()!==1)return null;$s=$this->pdo->prepare('SELECT * FROM webauthn_challenges WHERE id=:id');$s->execute([':id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null; }
    public function activeForDevice(int $userId,string $deviceId):array { $s=$this->pdo->prepare('SELECT * FROM vault_quick_unlock_credentials WHERE user_id=:u AND device_id=:d AND status IN ("active","pending") ORDER BY id ASC');$s->execute([':u'=>$userId,':d'=>$deviceId]);return$s->fetchAll()?:[]; }
    public function findActiveByCredential(int $userId,string $deviceId,string $credentialId):?array { $s=$this->pdo->prepare('SELECT * FROM vault_quick_unlock_credentials WHERE user_id=:u AND device_id=:d AND credential_id=:c AND status IN ("active","pending") LIMIT 1');$s->bindValue(':u',$userId,PDO::PARAM_INT);$s->bindValue(':d',$deviceId);$s->bindValue(':c',$credentialId,PDO::PARAM_LOB);$s->execute();$r=$s->fetch();return is_array($r)?$r:null; }
    public function insertCredential(array $d):void { $s=$this->pdo->prepare('INSERT INTO vault_quick_unlock_credentials (quick_unlock_id,user_id,device_id,credential_id,credential_record,signature_counter,quick_unlock_profile_version,prf_input,wrapped_vault_key,status,activated_at) VALUES (:q,:u,:d,:c,:r,:n,1,:p,:w,:st,IF(:st2="active",UTC_TIMESTAMP(),NULL))');$s->bindValue(':q',$d['quick_unlock_id']);$s->bindValue(':u',$d['user_id'],PDO::PARAM_INT);$s->bindValue(':d',$d['device_id']);$s->bindValue(':c',$d['credential_id'],PDO::PARAM_LOB);$s->bindValue(':r',$d['credential_record']);$s->bindValue(':n',$d['signature_counter'],PDO::PARAM_INT);$s->bindValue(':p',$d['prf_input'],PDO::PARAM_LOB);$s->bindValue(':w',$d['wrapped_vault_key'],PDO::PARAM_LOB);$s->bindValue(':st',$d['status']);$s->bindValue(':st2',$d['status']);$s->execute(); }
    public function updateAssertion(string $id,string $record,int $counter):void { $s=$this->pdo->prepare('UPDATE vault_quick_unlock_credentials SET credential_record=:r,signature_counter=:n,last_used_at=UTC_TIMESTAMP() WHERE quick_unlock_id=:q AND status="active"');$s->execute([':r'=>$record,':n'=>$counter,':q'=>$id]); }
    public function activate(string $id,string $wrapped,string $record,int $counter):void { $s=$this->pdo->prepare('UPDATE vault_quick_unlock_credentials SET status="active",wrapped_vault_key=:w,credential_record=:r,signature_counter=:n,activated_at=UTC_TIMESTAMP(),last_used_at=UTC_TIMESTAMP() WHERE quick_unlock_id=:q AND status="pending"');$s->bindValue(':w',$wrapped,PDO::PARAM_LOB);$s->bindValue(':r',$record);$s->bindValue(':n',$counter,PDO::PARAM_INT);$s->bindValue(':q',$id);$s->execute(); }
    public function revoke(int $userId,string $id):bool { $s=$this->pdo->prepare('UPDATE vault_quick_unlock_credentials SET status="revoked",revoked_at=UTC_TIMESTAMP() WHERE user_id=:u AND quick_unlock_id=:q AND status IN ("active","pending")');$s->execute([':u'=>$userId,':q'=>$id]);return$s->rowCount()===1; }
    public function revokeByDevice(int $userId, string $deviceId): int { $s=$this->pdo->prepare('UPDATE vault_quick_unlock_credentials SET status="revoked",revoked_at=UTC_TIMESTAMP() WHERE user_id=:u AND device_id=:d AND status IN ("active","pending")');$s->execute([':u'=>$userId,':d'=>$deviceId]);return$s->rowCount(); }
    public function findById(int $userId,string $id):?array { $s=$this->pdo->prepare('SELECT * FROM vault_quick_unlock_credentials WHERE user_id=:u AND quick_unlock_id=:q LIMIT 1');$s->execute([':u'=>$userId,':q'=>$id]);$r=$s->fetch();return is_array($r)?$r:null; }
}
